apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - metrics-reader-clusterrole.yaml
  - metrics-reader-clusterrolebinding.yaml
