# Build the manager binary
FROM registry.access.redhat.com/ubi9/go-toolset@sha256:1a755651ffe1a438f137418d183f18ebad527ec929206c17804f93490a97869e as builder

WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum

# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY . .

# Build
USER root
RUN CGO_ENABLED=1 GOEXPERIMENT=strictfipsruntime GOOS=linux go build -a -o manager cmd/main.go

# Runtime
FROM registry.redhat.io/ubi9/ubi-minimal-pqc@sha256:ef0438e9f078e71a7317c247fdf1d09644441fefe1fe26efbde5f4fa201435fb

WORKDIR /
COPY --from=builder /workspace/manager .
COPY manifests/trainer/ /opt/manifests-template/
COPY manifests/runtimes/ /opt/runtimes-template/
COPY manifests/imagestreams/ /opt/imagestreams-template/
USER 65532:65532

ENTRYPOINT ["/manager"]

LABEL com.redhat.component="odh-trainer-operator-rhel9" \
      name="rhoai/odh-trainer-operator-rhel9" \
      description="odh-trainer-operator" \
      summary="odh-trainer-operator" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-trainer-operator" \
      io.k8s.description="odh-trainer-operator" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
