# Build the manager binary
FROM registry.access.redhat.com/ubi9/go-toolset@sha256:15c3098dc4639e8a0e6a1bc77b50964513a1d76dccae4b07b9808101c5addd04 as builder

WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum

# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY . .

# Build
USER root
RUN CGO_ENABLED=1 GOEXPERIMENT=strictfipsruntime GOOS=linux go build -a -o manager cmd/main.go

# Runtime
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:984df0a2b8d9011d419b0ad260b25f6b74b7ce69ab0595b75522e30f8849f27f

WORKDIR /
COPY --from=builder /workspace/manager .
COPY manifests/trainer/ /opt/manifests-template/
COPY manifests/runtimes/ /opt/runtimes-template/
COPY manifests/imagestreams/ /opt/imagestreams-template/
USER 65532:65532

ENTRYPOINT ["/manager"]

LABEL com.redhat.component="odh-trainer-operator-rhel9" \
      name="rhoai/odh-trainer-operator-rhel9" \
      description="odh-trainer-operator" \
      summary="odh-trainer-operator" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-trainer-operator" \
      io.k8s.description="odh-trainer-operator" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
